# Generated by Django 5.0.6 on 2024-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Frontend', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Add Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='default_icon.png', max_length=100),
        ),
    ]
