# Generated by Django 5.0.6 on 2024-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Add description here'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Other', 'Other')], default='Frontend', max_length=50),
        ),
    ]
