# Generated by Django 5.0.6 on 2024-07-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_description_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Add description here'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project_images/default_icon.png', upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
