# Generated by Django 5.0.6 on 2024-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_title_remove_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(choices=[('HTML-CSS', 'HTML-CSS'), ('Javascript', 'Javascript'), ('React', 'React'), ('Node.js', 'Node.js'), ('Django', 'Django')], default='', max_length=50),
        ),
    ]
